### ISSUE TITLE
Develop a mechanism to pass cluster-dependent arguments during a module orchestration 

### ISSUE THREAD

**Issue by shlomitk1** [mesh-for-data/mesh-for-data#225]
**Problem statement:** 
Manager selects a module based on M4DModule set running on a coordinator cluster. The module arguments include some values that are cluster dependent, such as URL of some instance to connect to in a selected cluster, thus can not be configured in a M4DModule directly. 
A possible solution would be to apply a local instance of the module in a remote cluster that will include the specific values, and use the local instance to override the values during the orchestration.

**Comment by shlomitk1** [comment]
Requirements:
We want to propagate some of the decisions to the local cluster level (Blueprint, Blueprint controller running in the remote cluster). 
Another requirement is to enable an easier module development when there is no forced connection between module arguments and the manager knowledge of the module (we do not want to change module arguments structure).
Proposed solution:
- M4DModule is deployed only in coordinator cluster.
- Optionally, spec of the module will allow attach environment similar to the way it works with pods.
```
spec:
...
  env:
    - name:
       value:
   envfrom:
      - configMapRef:
             name:
       - secretRef:
             name:
```
The first part (env) is used for variable defaults - add a variable with its default value for all possible deployments. Names/Values are propagated through blueprint as an addition to module arguments. It is optional.
The second part (envfrom) provides instructions to the BlueprintController where to look for cluster-specific values. Configmap/secret names are propagated to the BlueprintController, the values take precedence over all module arguments including env part. Optional as well.
Example: a module receives jobNumber, url, username and password arguments.
M4DModule spec will look like:
```
env:
  - name: jobNumber
  - value: 1
envfrom:
   - configMapRef:
      name: module-config
    - secretRef:
      name: module-secret
```
      
A local cluster will deploy a module-config configmap with jobNumber and url variables, module-secret with username and password. If the configmap does not include jobNumber, the default value 1 will be taken.

**Comment by revit13** [comment]
@shlomitk1 how does the BlueprintController will get the instructions on where to look for cluster-specific values? Will the Blueprint contain it? Your suggestion seems to answers the requirements as far as I understand them. Unfortunately, I am not familiar with all Kubernetes features so I do not have an alternative approach for a solution if such exists.

**Comment by shlomitk1** [comment]
> 
> 
> @shlomitk1 how does the BlueprintController will get the instructions on where to look for cluster-specific values? Will the Blueprint contain it? Your suggestion seems to answers the requirements as far as I understand them. Unfortunately, I am not familiar with all Kubernetes features so I do not have an alternative approach for a solution if such exists.

Blueprint will contain the environment directives (name of the configmap, secret). The resources themselves (configmap,secret) will be deployed in advance in remote clusters in m4d-system.

**Comment by roee88** [comment]
Do we really need something from manager to support this? Can't it be part of the module itself?

**Comment by shlomitk1** [comment]
> 
> 
> Do we really need something from manager to support this? Can't it be part of the module itself?

We need:
1. A declaration of what a module needs (to avoid mistakes of a module requiring one resource and a cluster admin deploying another). 
2. It would be nice to provide defaults and having an ability to deploy module even when the resources are partially (or not at all) deployed in the remote cluster.
3. A centralized way to manage the module environment rather than having each module developer address these issues.

**Comment by roee88** [comment]
I guess that what I don't understand is what functionality is added that would not be achieve by putting these in the existing `spec.charts.values` (with no code changes). Can you explain please?

**Comment by shlomitk1** [comment]
> 
> 
> I guess that what I don't understand is what functionality is added that would not be achieve by putting these in the existing `spec.charts.values` (with no code changes). Can you explain please?
> 
> Edit: I understand that there could be some special functionality, e.g., around validation. I'm just trying to get it clearer because it's not obvious to me.

If M4DModule is deployed only in the coordinator cluster, we can't use the existing spec.charts.values to reflect settings specific to remote clusters. That's why we need to deploy different environments on different cluster, and let the module specify with what environment it works.

**Comment by roee88** [comment]
For example
```
spec:
...
  chart:
    values:
    - "jobNumber": "1"
    - "configMapRef": "module-config"
    - "secretRef": "module-secret"
```

**Comment by shlomitk1** [comment]
Ok. My concerns were regarding reading secrets/configmaps. Each module can address these issues on its own, of course.
