### ISSUE TITLE
Back-to-back installs fail

### ISSUE THREAD

**Issue by elsalant** [mesh-for-data/mesh-for-data#463]
The first installation on a new cluster failed (hack/install.sh) on a post-installation check for egeria.  I ended the third_party/egeria directory, did a deploy.sh deploy and it completed.  I tried reexecuting the install.sh and got:
make[1]: Entering directory '/home/salant/the-mesh-for-data/charts'
Installing vault ...
kubectl create namespace m4d-system || true
Error from server (AlreadyExists): namespaces "m4d-system" already exists
helm repo add hashicorp https://helm.releases.hashicorp.com
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/salant/.kube/kind-kubeconfig.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/salant/.kube/kind-kubeconfig.yaml
"hashicorp" already exists with the same configuration, skipping
helm install vault hashicorp/vault --version 0.9.1 \
                --set "global.openshift=false" \
                --set "server.dev.enabled=true" \
        --values ../third_party/vault/plugin-secrets-kubernetes-reader/values.yaml \
        --namespace m4d-system \
        --wait --timeout 120s
Error: cannot re-use a name that is still in use
make[1]: *** [Makefile:27: vault] Error 1
make[1]: Leaving directory '/home/salant/the-mesh-for-data/charts'
make: *** [Makefile:59: cluster-prepare] Error 2

There needs to be a check if "vault" exist, or do a helm uninstall vault before trying to install the Helm chart.

**Comment by roee88** [comment]
A lot have changed since this issue was opened. I'm closing but feel free to open another issue with a description of what is expected using the current instructions
