### ISSUE TITLE
Dependencies: bump controller-tools

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#501]
The version of controller-tools that we use today generates deprecated resources (CRDs, webhooks). Bumping to 0.5.0 (currently latest) will solve this while still preserving compatibility with Kubernetes 1.16+.

**Comment by froesef** [comment]
I tried to upgrade controller-tools and many different other libraries. In the end I can generate the v1 CRDs fine but when the status of the plotter is updated (`r.Status().Update(ctx, &plotter)`) somehow parts of the status vanish (the map that contains the status of cluster name to blueprint metadata contains the entry for the cluster but the MetaBlueprint is completely empty. Thus there seem to be problems with maps in the status.

**Comment by roee88** [comment]
Do you have a branch for that in your fork?
