### ISSUE TITLE
chore: move charts/Makefile targets to root Makefile and third_party

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#515]
* cert-manager should move to third_party
* vault should move to third_party
* m4d should move to root
* run-integration-tests should be removed

If splitting install from wait actually helps to CI performance we should do the split as we had before

**Comment by revit13** [comment]
@roee88 regrading "m4d should move to root" - do you refer to the directories themselves (charts/m4d and charts/m4d-crd) or only to the helm install instruction which should be moved to Makefile in root directory? Can you please elaborate on If "splitting install from wait actually helps to CI performance we should do the split as we had before". Thanks

**Comment by roee88** [comment]
> do you refer to the directories themselves (charts/m4d and charts/m4d-crd) or only to the helm install instruction which should be moved to Makefile in root directory

The make target only, not the directories.

> Can you please elaborate on If "splitting install from wait actually helps to CI performance we should do the split as we had before"

I think we can ignore this one, the CI works fine. Just for completion, earlier we didn't use `--wait` when installing but rather installed everything and then waited for everything at once. This is more complex but could save a few CI minutes. It was meaningful on Travis but it's less relevant now I think.
