### ISSUE TITLE
charts: remove hardcoded m4d-system in default vault address

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#521]
Currently this value is hardcoded in https://github.com/IBM/the-mesh-for-data/blob/9cf125f1ca0551a54a85e89cca87b547dd896fc2/charts/m4d/values.yaml#L79

Instead, either use {{ .Release.Namespace }} and pass the value to `tpl` function, or change the manager code to fully qualify local hostnames.

**Comment by revit13** [comment]
@roee88 does the above change will work if the vault address does not contain m4d-system, for example, if the address in of ingress or route o Vault?

**Comment by roee88** [comment]
>@roee88 does the above change will work if the vault address does not contain m4d-system, for example, if the address in of ingress or route o Vault?

Sure. I wrote two options that I could think of:
1. `use {{ .Release.Namespace }} and pass the value to tpl function` - This option will just allow using values in the values (yes). It won't force anything though.
2.  `change the manager code to fully qualify local hostnames.` - If you can write a function that really can differentiate between local endpoints and external endpoint then no problem. Otherwise it may be an issue.
