### ISSUE TITLE
docs: use localstack in quickstart notebook sample 

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#548]
Use localstack instead of MinIO because of MinIO issues with stocator (and hence the copy module)

Installing localstack:
```bash
helm repo add localstack-charts https://localstack.github.io/helm-charts
helm install localstack localstack-charts/localstack --set startServices="s3" --set service.type=ClusterIP
```

Uploading a file to localstack:
```bash
ENDPOINT=http://localstack:4566
BUCKET=demo
FILEPATH=test.txt
OBJECT_KEY=my-sample.csv

kubectl run awscli --image amazon/aws-cli:2.1.39 --command -- bash -c "yum install -y tar && sleep infinity"
kubectl cp ${FILEPATH} awscli:payload
kubectl exec awscli -- bash -c "aws configure set aws_access_key_id test && aws configure set aws_secret_access_key test && aws --endpoint-url=${ENDPOINT} s3api create-bucket --bucket ${BUCKET} && aws --endpoint-url=${ENDPOINT} s3api put-object --bucket ${BUCKET} --key ${OBJECT_KEY} --body payload"
```

**Comment by froesef** [comment]
I'm using https://github.com/adobe/S3Mock in the mover tests and it works fine. It's a docker image so it could also be deployed in Kubernetes.

**Comment by revit13** [comment]
@roee88 I get an error when executing the localstack instructions on openshift - I get "You need to be root to perform this command." I am trying to see if adding ocadm commands will resolve that.

**Comment by roee88** [comment]
In "Uploading a file" commands? Might be better to replace this part with something that doesn't run in Kubernetes if it's an issue.
