### ISSUE TITLE
Implicit Copy Module not listed as module in website documentation

### ISSUE THREAD

**Issue by simanadler** [mesh-for-data/mesh-for-data#577]
In the module description in the website (https://ibm.github.io/the-mesh-for-data/v0.1/concepts/modules/) the implicit copy module is not mentioned, only the arrow-flight module.  

As per a discussion with @roee88 we need proper documentation for it which also includes installing datashim, setting up the account resource, etc.

@froesef @roee88 @ronenkat

**Comment by revit13** [comment]
@roee88 @ronenkat does it makes sense to show the copy module scenario by adding another notebook example similar to the one that currently exists but this time with `required: true` in the spec.data.copy field in M4DApplication? it will be using the same single cluster as in the existing notebook example but as @simanadler wrote it will require additional resources to handle the copy.
