### ISSUE TITLE
Policy manager response json schema structure

### ISSUE THREAD

**Issue by ritwikc** [mesh-for-data/mesh-for-data#604]
While finalizing the policy manager json schema structure it has been decided that in the module.structs.schema.json the action will include name and the associated required field on which the action has been taken. For example if the action is "RedactColumn" the required field is "columns" which is a list of strings, that is the array of column names on which the action "RedactColumn" has been performed. This change was made to make it in accordance with the response provided in the [google document](https://docs.google.com/document/d/1YjMWZyZd9rQvRU8TcQzg6E1zCYfA_cZ5wuUCJier4oA/edit#)

Previously, the module.structs.schema.json used to contain the "transformation" with the name of the transformation with an array of  optional parameters associated with the transformation. It also included the level at which the transformation is made. Essentially level used to contain the code (i.e 0: unknown, 1: dataset, 2: column, 3: row, 4: cell) along with the name of transformed entity, be it a dataset, column, row or a cell.   

This issue is linked to PR #558

**Comment by roee88** [comment]
I'm not sure what's the issue here. @simanadler ?

**Comment by simanadler** [comment]
@roee88 If I understand correctly this is the change you requested to include the name rather than the whole transform structure in the policy manager response.  Right @ritwikc ?

**Comment by roee88** [comment]
I didn't suggest that. I only said that we should start simple in M4DModule, just specifying the names of supported actions.

**Comment by roee88** [comment]
@ritwikc I think we can close this unless you meant something else

**Comment by ritwikc** [comment]
Closed the issue for now.
