### ISSUE TITLE
Refactor website landing page

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#611]
The current website is a little awkward. There is an about page which is the landing zone (e.g. https://ibm.github.io/the-mesh-for-data/v0.1/), however, most of the initial user information is here: https://ibm.github.io/the-mesh-for-data/v0.1/concepts/introduction/ which is a little hard to find.

_Originally posted by @butler54 in https://github.com/mesh-for-data/mesh-for-data/discussions/588_

**Comment by ronenkat** [comment]
Tasks:
- [ ] Create mesh-for-data.github.io website
- [ ] Add support for a blog on mesh-for-data website
- [ ] Move base content to root mesh-for-data homepage
