### ISSUE TITLE
Change blueprint manager to be namespace scoped

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/mesh-for-data#629]
Currently the blueprint controller will respond to events on Blueprint resources that are created outside of m4d-blueprints. This should change.

**Comment by simanadler** [comment]
@roee88 My understanding is that today the resource charts are deployed by the blueprint manager to the same namespace as the blueprint, and that the blueprint's namespace is always "m4d-blueprints" (constant defined in plotter_controller.go).  

Assuming this is correct (and maybe it's not) to what events from outside of m4d-blueprints do you refer?  Who/what created them?

**Comment by roee88** [comment]
Anyone. Say that I was given a namespace to operate on and I'm the admin of that namespace (typical usage I think). Then I can create a Blueprint directly. This is not the intended use.

**Comment by simanadler** [comment]
@roee88 OK.  So you are saying that we want the blueprint reconciler to check that the event it received is from namespace "m4d-blueprints", and if it's not it will ignore it.  Right?

**Comment by roee88** [comment]
That's a simple solution! nice. I was originally aiming for a solution where it doesn't even monitor for Blueprint events in anything other than m4d-blueprints, I don't know if it's possible.

**Comment by simanadler** [comment]
@roee88 There is a way to register a filter so that the events won't reach the reconciler.  That's the approach I will take if that's OK with you.  I will create a filter that checks the namespace of the event.  If it isn't m4d-blueprints then the event won't reach the reconciler.
