### ISSUE TITLE
allow empty m4dapplication( without any dataset) creation

### ISSUE THREAD

**Issue by lappanna** [mesh-for-data/mesh-for-data#639]
Creating an empty m4dapplication without any dataset fails with below error
```
* spec.data.dataSetID: Required value
 ```

**Comment by shlomitk1** [comment]
@lappanna What should be the value of status.ready for an M4DApplication with no datasets? False? True? Are you waiting for True in order to proceed with adding the data assets?

**Comment by lappanna** [comment]
@shlomitk1 status.ready should be true for M4DApplication with no datasets.
