### ISSUE TITLE
Python error: NoneType object is not subscriptable - on Kind v0.11.0

### ISSUE THREAD

**Issue by weberjanet** [mesh-for-data/mesh-for-data#672]
If I follow the steps in https://mesh-for-data.github.io/mesh-for-data/v0.2/get-started/quickstart/ and https://mesh-for-data.github.io/mesh-for-data/v0.2/samples/notebook/ using a Kind v0.11.0 cluster, the result is:
```
---------------------------------------------------------------------------
FlightServerError                         Traceback (most recent call last)
<ipython-input-2-affc70c65584> in <module>
     14 
     15 # Send request and fetch result as a pandas DataFrame
---> 16 info = client.get_flight_info(fl.FlightDescriptor.for_command(json.dumps(request)))
     17 reader: fl.FlightStreamReader = client.do_get(info.endpoints[0].ticket)
     18 df: pd.DataFrame = reader.read_pandas()

/opt/conda/lib/python3.9/site-packages/pyarrow/_flight.pyx in pyarrow._flight.FlightClient.get_flight_info()
/opt/conda/lib/python3.9/site-packages/pyarrow/_flight.pyx in pyarrow._flight.check_flight_status()
FlightServerError: 'NoneType' object is not subscriptable. Detail: Python exception: TypeError
```

**Comment by revit13** [comment]
The arrow-flight module log indicates `claim "iss" is invalid` error recieved from Vault. 


   `30/06/2021 18:55:02 - CRITICAL - about to run AFMFlightServer

   30/06/2021 18:56:09 - CRITICAL - reading s3 configuration
   30/06/2021 18:56:09 - CRITICAL - reading s3 configuration from vault
   30/06/2021 18:56:09 - CRITICAL - jwt_file_path = /var/run/secrets/kubernetes.io/serviceaccount/token
   30/06/2021 18:56:09 - CRITICAL - vault_address = http://vault.m4d-system:8200
   30/06/2021 18:56:09 - CRITICAL - secret_path = /v1/kubernetes-secrets/paysim-csv?namespace=m4d-notebook-sample
   30/06/2021 18:56:09 - CRITICAL - vault_auth = /v1/auth/kubernetes/login
   30/06/2021 18:56:09 - CRITICAL - role = module
   30/06/2021 18:56:09 - CRITICAL - Got error code 500 from Vault authentication
   30/06/2021 18:56:09 - CRITICAL - Error response: {'errors': ['claim "iss" is invalid']}
   30/06/2021 18:56:09 - CRITICAL - Empty vault authorization response`

it is related to kubernetes auth method configuration in vault - `issuer` must be specified now when configuring vault (https://www.hashicorp.com/blog/retrieve-hashicorp-vault-secrets-with-kubernetes-csi), 

When adding the  `issuer` to the configuraton the sample fails on kind version lower than v0.11.0. 
There might be two options to solve this: 
one is to add `disable_iss_validation=true` to vault configuration. which is insecure:

      `$vault write auth/kubernetes/config \
        token_reviewer_jwt="$SA_JWT_TOKEN" \
        kubernetes_host="$K8S_HOST" \
        kubernetes_ca_cert="$SA_CA_CRT" \
        disable_iss_validation=true`
and the other is to write a different values.yaml file for the different kind versions. @ronenkat @roee88 I appricaite your opions on this, Thankks

**Comment by revit13** [comment]
kind v0.11.0 uses kubernetes v1.21 by default so should we choose the yaml file based on the kubernetes version? Thanks
